  METHOD prepare_update_limit.
    CONCATENATE
    '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">'
       '<soapenv:Header/>'
       '<soapenv:Body>'
          '<tem:Kurum_OnlineKEK>'
             '<!--Optional:-->'
             '<tem:baseInputData>'
             '<![CDATA['
             '<BaseInput>'
                 '<BaseMusteriNo>' ms_service_info-additional_field1 '</BaseMusteriNo>'
                 '<BaseKurumKodu>' ms_service_info-additional_field1 '</BaseKurumKodu>'
                 '<BaseKurumKullanici>' ms_service_info-username '</BaseKurumKullanici>'
                 '<BaseKurumSifre>' ms_service_info-password '</BaseKurumSifre>'
                 '<BaseKurumOperasyon>SorgulaLimit</BaseKurumOperasyon>'
                 '<BaseBinlikAyrac></BaseBinlikAyrac>'
                 '<BaseOndalikAyrac>.</BaseOndalikAyrac>'
                 '<BaseInputData>'
                     '<DTOLimitIstek>'
                         '<AnaFirmaKurumUrunTanimId>' ms_service_info-additional_field2 '</AnaFirmaKurumUrunTanimId>'
                         '<AnaFirmadakiBayiKodu>' ms_subscribe-subscriber_number '</AnaFirmadakiBayiKodu>'
                   '</DTOLimitIstek>'
                 '</BaseInputData>'
             '</BaseInput>'
             ']]>'
          '</tem:baseInputData>'
          '</tem:Kurum_OnlineKEK>'
       '</soapenv:Body>'
    '</soapenv:Envelope>'
    INTO rv_request.
  ENDMETHOD.