  METHOD if_oo_adt_classrun~main.
    DATA lt_error TYPE TABLE OF ydbs_t_gar_error.
    lt_error = VALUE #( ( code = '0101' message = 'Mükerrer BatchID.' )
                        ( code = '0102' message = 'ProcessingFlag hatalı.' )
                        ( code = '0103' message = 'PackageCount sıfır olamaz.' )
                        ( code = '0104' message = 'Kurum inaktif.' )
                        ( code = '0105' message = 'MainOperationCode hatalı.' )
                        ( code = '0199' message = 'Diğer Hata' )

                        ( code = '0201' message = 'Mükerrer paket.' )
                        ( code = '0202' message = 'Geçersiz BatchID.' )
                        ( code = '0204' message = 'PackageID geçersiz.' )
                        ( code = '0205' message = 'PackageID sıralama hatası.' )
                        ( code = '0206' message = 'PackageItemCount hatalı.' )
                        ( code = '0207' message = 'Paket içinde mükerrer kayıt. LogoUniqueID tekrar edilmiş.' )
                        ( code = '0208' message = 'Kurum bulunamadı veya inaktif.' )
                        ( code = '0299' message = 'Diğer Hata' )

                        ( code = '0301' message = 'Mükerrer BatchTrailer.' )
                        ( code = '0302' message = 'Beklenmeyen BatchTrailer.' )
                        ( code = '0304' message = 'BatchItemCount hatalı.' )
                        ( code = '0306' message = 'PackageCount hatalı.' )
                        ( code = '0399' message = 'Diğer hata.' )

                        ( code = '0401' message = 'Data tipi/formatı hatalı.' )
                        ( code = '0402' message = 'Zorunlu saha eksik.' )
                        ( code = '0403' message = 'Transfer tipi için hatalı bilgi' )
                        ( code = '0404' message = 'Borçlu hesap tanımlı değil.' )
                        ( code = '0405' message = 'Borçlu hesap ilgili işlem için kullanılamaz.' )
                        ( code = '0406' message = 'Alacak banka hatalı.' )
                        ( code = '0407' message = 'Alacak şube hatalı' )
                        ( code = '0408' message = 'Alacak hesap hatalı' )
                        ( code = '0409' message = 'Tutar sıfır olamaz.' )
                        ( code = '0410' message = 'TRL için tutar kuruşlu olamaz.' )
                        ( code = '0412' message = 'Borçlu/Alacaklı/Tutar döviz kodları uyumsuz.' )
                        ( code = '0413' message = 'EFT ise Döviz kodu TRL olmalı.' )
                        ( code = '0414' message = 'Vade tarihi geçmiş tarih olamaz.' )
                        ( code = '0415' message = 'EFT için vade tarihi tatil günü olamaz.' )
                        ( code = '0416' message = 'Kurum bulunamadı/inaktif.' )
                        ( code = '0417' message = 'Borçlu Hesap Kapalı' )
                        ( code = '0418' message = 'Alacak Hesap Kapalı' )
                        ( code = '0419' message = 'VKN formatı hatalı.' )
                        ( code = '0420' message = 'VKN bilgisi hatalı' )
                        ( code = '0421' message = 'IBAN diğer bankalara ait geçerli bir IBAN olmalıdır.' )
                        ( code = '0422' message = 'Online YP havale işlemlerinde kullanılacak borçlu hesabın döviz kodu YTL olmalıdır.' )
                        ( code = '0423' message = 'Online YP havale işlemlerinde ödemenin döviz kodu YTL olamaz.' )
                        ( code = '0424' message = 'Alacaklı YP hesabın döviz kodu ödeme döviz kodundan farklı olamaz.' )
                        ( code = '0425' message = 'Alacaklı YP ve alacaklı YTL hesapların müşterileri farklı olamaz.' )
                        ( code = '0426' message = 'PaymentType I olan işlemler için vade tarihi olmamalıdır.' )
                        ( code = '0427' message = 'Tarih günün tarihinden küçük olamaz.' )
                        ( code = '0428' message = 'Daha önce bu TrfUniqueID ile işlem yapılmamış.' )
                        ( code = '0429' message = 'IBAN Garanti Bankası’na ait geçerli bir IBAN olmalıdır.' )
                        ( code = '0430' message = 'TC Kimlik no formatı hatalı.' )
                        ( code = '0431' message = 'TC Kimlik no bilgisi hatalı.' )
                        ( code = '0432' message = 'IBAN hatalı' )
                        ( code = '0433' message = 'Ödeme tipi hatalı' )
                        ( code = '0434' message = 'Kur hatası' )
                        ( code = '0499' message = 'Diğer Hata' )

                        ( code = '0501' message = 'Bakiye Yetersiz' )
                        ( code = '0502' message = 'Ödeme Geri Alındı' )
                        ( code = '0504' message = 'Alacak Hesap Kapalı' )
                        ( code = '0505' message = 'Alacak Hesap Yok/Bulunamadı' )
                        ( code = '0507' message = 'Borçlu Hesap Kapalı' )
                        ( code = '0508' message = 'Borçlu Hesap Yok/Bulunamadı' )
                        ( code = '0510' message = 'Kurum Aktif Değil/Bulunamadı' )
                        ( code = '0599' message = 'Diğer Hata' )

                        ( code = '0601'    message = 'Data tipi/formatı hatalı.' )
                        ( code = '0602'    message = 'Zorunlu saha eksik.' )
                        ( code = '0603'    message = 'Eklenmek istenen kayıt mevcut.' )
                        ( code = '0604'    message = 'Değiştirilmek istenen kayıt bulunamadı.' )
                        ( code = '0605'    message = 'Değiştirilmek istenen kayıt işlem görmüş.' )
                        ( code = '0606'    message = 'Silinmek istenen kayıt bulunamadı.' )
                        ( code = '0607'    message = 'Silinmek istenen işlem görmüş.' )
                        ( code = '0608'    message = 'Borç bayi/öğrenci/tesisat tanımsız.' )
                        ( code = '0609'    message = 'Borç bayi inaktif.' )
                        ( code = '0610'    message = 'Alacak bayi tanımsız.' )
                        ( code = '0611'    message = 'Alacak bayi inaktif.' )
                        ( code = '0612'    message = 'Fatura döviz kodu hatalı.' )
                        ( code = '0613'    message = 'Vade günün tarihinden küçük' )
                        ( code = '0614'    message = 'Tutar sıfır olamaz.' )
                        ( code = '0615'    message = 'TRL için kuruş olamaz.' )
                        ( code = '0616'    message = 'Bölge/dönem aktif değil/bulunamadı' )
                        ( code = '0617'    message = 'Kurum aktif değil/bulunamadı' )
                        ( code = '0618'    message = 'Borç ve alacak bayiler aynı' )
                        ( code = '0619'    message = 'Ana operasyon kodları uyumsuz.' )
                        ( code = '0622'    message = 'Mesaj anahtarı daha önce kullanılmıştır.' )
                        ( code = '0623'    message = 'İşlem türü geçersizdir.' )
                        ( code = '0624'    message = 'Döviz kodu YTL olmalıdır.' )
                        ( code = '0625'    message = 'Kayıt tipi geçersizdir.' )
                        ( code = '0626'    message = 'Bloke tutarı kullanılabilir limitten fazla.' )
                        ( code = '0627'    message = 'Fatura tutarı açık bloke tutarını aşmamalıdır.' )
                        ( code = '0628'    message = 'Faturaya ait bloke kaydı bulunamadı.' )
                        ( code = '0629'    message = 'Aynı mesaj daha önce işleme alınmıştır.' )
                        ( code = '0630'    message = 'Referans numarası daha önce kullanılmıştır.' )
                        ( code = '0631'    message = 'Açık bloke tutarı uygun değil.' )
                        ( code = '0632'    message = 'Bayi bulunamadı. ' )
                        ( code = '0699'    message = 'Diğer Hata.' )

                        ( code = '0700'    message = 'Tamamı tahsil edildi.' )
                        ( code = '0701'    message = 'Kısmi tahsil edildi.' )
                        ( code = '0702'    message = 'Bakiye yetersiz.' )
                        ( code = '0704'    message = 'Bakiye yetersiz-Blokeli' )
                        ( code = '0705'    message = 'Limit yetersiz.' )
                        ( code = '0706'    message = 'Mahsup etti. (Faturanın tamamı kapandı)' )
                        ( code = '0707'    message = 'Mahsup etti. (Kısmi kapandı)' )
                        ( code = '0708'    message = 'Tamamı mahsup edildi.' )
                        ( code = '0709'    message = 'Kısmi mahsup edildi.' )
                        ( code = '0710'    message = 'Alacak hesap yok/bulunamadı/kapalı' )
                        ( code = '0711'    message = 'Borç hesap yok/bulunamadı/kapalı' )
                        ( code = '0712'    message = 'Bayi/öğrenci/tesisat aktif değil/bulunamadı' )
                        ( code = '0713'    message = 'Bölge/dönem aktif değil/bulunamadı' )
                        ( code = '0714'    message = 'Kurum aktif değil/bulunamadı' )
                        ( code = '0799'    message = 'Diğer Hata' )


                        ( code = '0801' message = 'Hesap kurumun MARS’ına bağlı olmalıdır.' )
                        ( code = '0802' message = 'Sadece vadesiz hesaplar için bakiye sorgulama yapılabilir' )
                        ( code = '0803' message = 'Şube kodu hatalı' )
                        ( code = '0804' message = 'Hesap hatalı' )
                        ( code = '0805' message = 'IBAN hatalı' )
                        ( code = '0806' message = 'TC Kimlik no formatı hatalı.' )
                        ( code = '0807' message = 'TC Kimlik no bilgisi hatalı.' )
                        ( code = '0808' message = 'VKN formatı hatalı.' )
                        ( code = '0809' message = 'VKN bilgisi hatalı' )

                        ( code = '9101' message = 'Hatalı sertifika no' )
                        ( code = '9102' message = 'Bu sertifika no ile ilgili işlem yapılamaz.' )
                        ( code = '9103' message = 'Sertifika şifre hatası.' )  ).
    MODIFY ydbs_t_gar_error FROM TABLE @lt_error.
    COMMIT WORK AND WAIT.
  ENDMETHOD.